when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
        prefix: /_error


test:
    path:       /test
    controller: App\Controller\TestController::show
    methods:    GET|HEAD

